[versions]

minecraft = "1.21.11"
parchment = "2025.12.20"

fabric-loader = "0.18.4"
fabric-api = "0.141.1+1.21.11"

[libraries]

minecraft = { module = "net.minecraft:minecraft", version.ref = "minecraft" }
parchment = { module = "org.parchmentmc.data:parchment-1.21.11", version.ref = "parchment" }

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
